export const ROUTES = {
  home: '/',
  tours: '/tours',
  tourDetail: (slug: string) => `/tours/${slug}`,
  category: (slug: string) => `/categories/${slug}`,
  search: '/search',
  about: '/about',
  contact: '/contact',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',

  account: '/account',
  favorites: '/favorites',
  cart: '/cart',
  checkout: '/checkout',
  checkoutResult: '/checkout/result',
  accountProfile: '/account/profile',
  accountBookings: '/account/bookings',
  accountBookingDetail: (code: string) => `/account/bookings/${code}`,
  accountPassword: '/account/password',

  blog: '/cam-nang',
  blogDetail: (slug: string) => `/cam-nang/${slug}`,

  admin: '/admin',
  adminBookings: '/admin/bookings',
  adminTours: '/admin/tours',
  adminTourNew: '/admin/tours/new',
  adminTourEdit: (id: string) => `/admin/tours/${id}`,
  adminCategories: '/admin/categories',
  adminBlog: '/admin/blog',
  adminBlogNew: '/admin/blog/new',
  adminBlogEdit: (id: string) => `/admin/blog/${id}`,
} as const
